# Generated by Django 2.2.4 on 2019-10-08 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Listing',
            new_name='listing',
        ),
    ]
